version: '3.9'
services:
  crawler:
    build:
      context: .
      dockerfile: dockers/Dockerfile.crawler
    restart: always
    volumes:
      - .:/app
    environment:
      - ES_SCHEMA=http
      - ES_HOST=es:9200
      - ES_INDEX=sahamyab-tweets
      - KAFKA_HOST=kafka:9092
    networks:
      - crawler-network
    depends_on:
      - es
      - kafka

  master-crawler:
    build:
      context: .
      dockerfile: dockers/Dockerfile.master-crawler
    restart: always
    volumes:
      - .:/app
    environment:
      - KAFKA_HOST=kafka:9092
    networks:
      - crawler-network
    depends_on:
      - kafka

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - crawler-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    ports:
      - 15601:5601
    networks:
      - crawler-network
    depends_on:
      - es

  zookeeper:
    image: 'bitnami/zookeeper:3.7.1'
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - crawler-network

  kafka:
    image: 'bitnami/kafka:3.2.1'
    ports:
      - '19092:9092'
    environment:
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - crawler-network
    depends_on:
      - zookeeper

volumes:
  es-data:

networks:
  crawler-network:
    driver: bridge
