FROM python:3.10-slim
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt ./

RUN python3.10 -m pip install -r requirements.txt

COPY . .

CMD bin/wait-for-it -t 120 $KAFKA_HOST -- echo "Kafka is up." && \
    python3 master-crawler.py --kafka-host $KAFKA_HOST -v
